# Generated by Django 4.2.20 on 2025-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_booking_distance_booking_drop_lat_booking_drop_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='airport_direction',
            field=models.CharField(blank=True, choices=[('pickup', 'Airport Pickup'), ('drop', 'Airport Drop')], max_length=10, null=True),
        ),
    ]
